Conectar despensa con recetas
didierrc/CompiComida pull request #57
Opened 2024-12-29 14:33 UTC by uo289549

Se arreglaron los bugs donde desaparences las unidades al rotar pantalla en las actividades de añadir y editar despensa y añadir producto a la lista

2024-12-29 21:15 UTC, Raulms29 requested changes
En lugar de hacer override a todas esas funciones, esto lo podrías hacer con el viewModel. En la vista de Añadir Producto a una lista (AddGroceryItemViewModel) yo lo hice para las categorías, debería ser muy similar en el caso de las unidades.

2024-12-30 14:53 UTC, uo289549 commented
> En lugar de hacer override a todas esas funciones, esto lo podrías hacer con el viewModel. En la vista de Añadir Producto a una lista (AddGroceryItemViewModel) yo lo hice para las categorías, debería ser muy similar en el caso de las unidades.

Estuve mirandolo, el problema para hacer eso es que las categorias son una entidad y por tanto en el view model utilizas la entidad para hacer el update; pero las unidades no son ninguna entidad simplemente son un array de strings almacenado en resources y desde el view model no puedo acceder a resources. Por tanto creo q es mejor dejar esos metodos override. ¿Tu que opinas?

2024-12-30 16:34 UTC, Raulms29 commented
> Estuve mirandolo, el problema para hacer eso es que las categorias son una entidad y por tanto en el view model utilizas la entidad para hacer el update; pero las unidades no son ninguna entidad simplemente son un array de strings almacenado en resources y desde el view model no puedo acceder a resources. Por tanto creo q es mejor dejar esos metodos override. ¿Tu que opinas?
Lo que podrías hacer si no puedes acceder desde el view model es pasárselo como parámetro en el constructor ya que no va a cambiar, así ya lo tendrías.

2025-01-01 14:49 UTC, didierrc requested changes
Lo veo bien pero hay conflictos. Resúelvelos porfa y lo acepto.

2025-01-05 18:58 UTC, didierrc approved these changes
Todo está bien. Buen trabajo!

2025-01-05 18:59 UTC, merged